version: '3.4'

services:
  todoapi:
    image: todoapi
    build:
      context: todo-api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4050:4050
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
