version: '3.4'

services:
  todoapi:
    image: jesus03m/todoapi
    environment:
      NODE_ENV: production
      REDIS_URL: "redis://redis:6379"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - './todo-api:/usr/src/app/server'

  todo-front:
    image: jesus03m/todofront
    environment:
      NODE_ENV: production
      REACT_APP_BASE_URL: ""
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - todoapi

  mysql:
    image: mysql
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=todo_prod
      - MYSQL_ROOT_PASSWORD=root
    command: --authentication_policy=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      retries: 10
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis
    networks:
      - app-network
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 10
    volumes:
      - ./data/redis:/data

networks:
  app-network:
    driver: "bridge"