version: '3.4'

services:
  todoapi:
    image: todoapi
    build:
      context: todo-api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REDIS_URL: "redis://redis:6379"
    # ports:
    #   - 5000:5000
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - './todo-api:/usr/src/app/server'
  todo-front:
    image: todofront
    build:
      context: todo-front
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REACT_APP_BASE_URL: ""
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - todoapi
  mysql:
    image: mysql
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=todo_prod
      - MYSQL_ROOT_PASSWORD=root
    command: --authentication_policy=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      retries: 10
    restart: always
    volumes:
      - c:/data/lib/mysql:/var/lib/mysql
  redis:
    image: redis
    networks:
      - app-network
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 10
    volumes:
      - c:/data/lib/redis:/data
networks:
  app-network:
    driver: "bridge"